### ISSUE TITLE
cron job: send out an email whenever errors status changes

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#23]
ATM we have no errors reported.  But initially we had and we could get new ones appearing... didn't look at the code -- do we exit with non-0 if errors appear?  @jwodder please check/make sure that emails go out if error would happen (I found no emails in my mailbox with webshot and cron in subject)

**Comment by jwodder** [comment]
@yarikoptic `make_webshots.py` only fails if an error occurs during login or a `WebDriverException` error occurs.  `TimeoutException`s and all other exceptions occuring while loading & interacting with a page just cause an error to be logged to the console and in place of the "time" value, but they don't affect the exit status.  Under what circumstances do you want the script to exit nonzero?

**Comment by jwodder** [comment]
As for cron e-mails, I don't know how you've configured e-mail on drogon, but if you're getting emails for other dandi@drogon cronjobs, then I'd say it's working correctly.

**Comment by yarikoptic** [comment]
let's assume that it works correctly since i do get other emails from `dandi@drogon` and it is just that we never got a new error

**Comment by yarikoptic** [comment]
FTR, I apparently did get an email recently whenever it failed to connect (for the first time, so nothing probably to deal with ATM):
```
+ xvfb-run python tools/make_webshots.py                                                                                                                                             
HEAD is now at 2ab6c4150 Automatically update webshots                                                                                                                               
Your branch is up to date with 'origin/master'.                                                                                                                                      
Already up to date.                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                   
  File "tools/make_webshots.py", line 244, in <module>                                                                                                                               
    driver = get_ready_driver()                                                                                                                                                      
  File "tools/make_webshots.py", line 221, in get_ready_driver                                                                                                                       
    login(driver, os.environ["DANDI_USERNAME"], os.environ["DANDI_PASSWORD"])                                                                                                        
  File "tools/make_webshots.py", line 81, in login                                                                                                                                   
    WebDriverWait(driver, 300).until(                                                                                                                                                
  File "/home/dandi/cronlib/dandi-api-webshots/venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until                                               
    raise TimeoutException(message, screen, stacktrace)                                                                                                                              
selenium.common.exceptions.TimeoutException: Message:  
```
