### ISSUE TITLE
split out tools/ into separate repo and make it parametric

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#27]
- split `tools/` away into `dandi-api-webshots-tools` repo, and link it back under `tools/` path as submodule
- script and cron helper should be given either full urls to web ui + api, or just instance name (`dandi` vs `dandi-staging` as known to dandi-cli)
- cron job should take care about merging possible changes in the `tools/`
- do the same "submodule" trick to https://github.com/dandi/dandi-api-webshots-staging

**Comment by jwodder** [comment]
@yarikoptic I don't have write permission to https://github.com/dandi/dandi-api-webshots-staging.

**Comment by yarikoptic** [comment]
sorry, you should be admin now

**Comment by jwodder** [comment]
Done.

**Comment by yarikoptic** [comment]
```
dandi@drogon:~/cronlib/dandi-api-webshots$ pwd
/home/dandi/cronlib/dandi-api-webshots
dandi@drogon:~/cronlib/dandi-api-webshots$ ls tools/
dandi@drogon:~/cronlib/dandi-api-webshots$ git submodule
-e8ab9b2959bebfc465a95725af77f9c45355e1b8 tools
```
so submodule was not initialized, did `submodule update --init` and tried invocation

```
flock -n -E 0 /home/dandi/.run/run-webshots.lock ~/cronlib/dandi-api-webshots/tools/run-webshots.sh dandi
```
to get
```
+ xvfb-run python tools/make_webshots.py -i dandi
Traceback (most recent call last):
  File "tools/make_webshots.py", line 361, in <module>
    main()
  File "/home/dandi/cronlib/dandi-api-webshots/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/cronlib/dandi-api-webshots/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dandi/cronlib/dandi-api-webshots/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/cronlib/dandi-api-webshots/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/make_webshots.py", line 311, in main
    with Webshotter(dandi_instance) as ws:
  File "tools/make_webshots.py", line 68, in __init__
    self.driver = self.get_driver()
  File "tools/make_webshots.py", line 92, in get_driver
    self.login(driver, os.environ["DANDI_USERNAME"], os.environ["DANDI_PASSWORD"])
  File "tools/make_webshots.py", line 99, in login
    self.wait_no_progressbar("v-progress-circular")
  File "tools/make_webshots.py", line 139, in wait_no_progressbar
    WebDriverWait(self.driver, 300, poll_frequency=0.1).until(
AttributeError: 'Webshotter' object has no attribute 'driver'
```
so I guess a bit more to be done?

**Comment by jwodder** [comment]
@yarikoptic That should be fixed now.

**Comment by yarikoptic** [comment]
ok, trying it now

**Comment by yarikoptic** [comment]
Thanks! works!
