### ISSUE TITLE
need to guard against "page crash"es

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#28]
while making a run for https://github.com/dandi/dandi-api-webshots-staging, it errored out with
```
2021-08-10T13:42:59-0400 [INFO    ] 000018 landing
2021-08-10T13:43:02-0400 [INFO    ] 000018 edit-metadata
2021-08-10T13:43:04-0400 [INFO    ] 000018 view-data
2021-08-10T13:43:07-0400 [INFO    ] 000019 landing
2021-08-10T13:43:09-0400 [INFO    ] 000019 edit-metadata
2021-08-10T13:43:12-0400 [INFO    ] 000019 view-data
2021-08-10T13:43:14-0400 [INFO    ] 000020 landing
2021-08-10T13:43:16-0400 [INFO    ] 000020 edit-metadata
Traceback (most recent call last):
  File "tools/make_webshots.py", line 277, in <module>
    stats = process_dandiset(driver, ds)
  File "tools/make_webshots.py", line 184, in process_dandiset
    act()
  File "tools/make_webshots.py", line 146, in click_edit
    edit_button.click()
  File "/home/dandi/cronlib/dandi-api-webshots-staging/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/dandi/cronlib/dandi-api-webshots-staging/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/dandi/cronlib/dandi-api-webshots-staging/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/dandi/cronlib/dandi-api-webshots-staging/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=73.0.3683.75)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.0-0.bpo.9-amd64 x86_64)
```
due to freshly reported https://github.com/dandi/dandiarchive/issues/835 .  webshotting script should just annotate that the dandiset/page errored out (as we already do for other circumstances such as time out IIRC), restart the driver, and proceed to the next one.

Now might be the "unique" opportunity to make it work due to existing crash.

**Comment by jwodder** [comment]
@yarikoptic The code already contains a provision for doing this, but it's deactivated (See the comment):

https://github.com/dandi/dandi-api-webshots-tools/blob/e8ab9b2959bebfc465a95725af77f9c45355e1b8/make_webshots.py#L235-L244

**Comment by yarikoptic** [comment]
hm, that sucks... thanks for digging it out.  I guess https://github.com/dandi/dandi-api-webshots/issues/19 should help to address that. I would like to get testing staging instance working, so we could "fire-and-forget" about ongoing effort to establish webshots for it, so please take care about #19.

**Comment by yarikoptic** [comment]
#19 was addressed and https://github.com/dandi/dandi-api-webshots-tools/pull/3 started to catch more. Let's hope that overall addressed
